#
# A metapackage to declare that an environment tracks (has) the "CUDA" feature.
#  - Tracks the cuda{version} feature.
#  - Shows a message to the user.
#
# Installs nothing, that could be left to a CUDA package that would also
# track the same feature.
#

{% extends "base.yaml" %}
{% block recipe %}

{% set name = "cuda-feature" %}

package:
  name: {{ name }}
  version: {{ cuda_version }}

build:
  number: 1
  track_features:
    - cuda{{ cuda_version }}

about:
  home: https://developer.nvidia.com/cuda-zone
  summary: A parallel computing platform and programming model.

{% endblock %}
