#
# A metapackage to declare that an environment tracks (has) the "cuDNN" feature.
#  - Tracks the cuda{version} feature.
#  - Shows a message to the user.
#
# Installs nothing, that could be left to a cuDNN package that would also
# track the same feature.
#

{% extends "base.yaml" %}
{% block recipe %}

{% set name = "cudnn-feature" %}

package:
  name: {{ name }}
  version: {{ cudnn_version }}

build:
  number: 1
  track_features:
    - cudnn{{ cudnn_version }}
  features:
    - cuda{{ cuda_version }}

about:
  home: https://developer.nvidia.com/cudnn
  summary: A GPU-accelerated library of primitives for deep neural networks.

extra:
  recipe-url: https://github.com/loopbio/cudnn-feature-feedstock
  recipe-maintainers:
    - sdvillal

{% endblock %}
